// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nubkmbhqszecpnlnktig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51YmttYmhxc3plY3BubG5rdGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDk5MjYsImV4cCI6MjA2MzkyNTkyNn0.JaGzV_nvjEkHQkFq_qiLTON-8Yh88LRrQR9JesZdnEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);